### ISSUE TITLE
So it must be login into facebook

### ISSUE THREAD

**Issue by JustSmile739** [fbsamples/live-comments-teleprompter#14]
Because i have a trouble with the login. It require a https web and that pretty hard for me to get the SSL. And i have a question that why we need to login even the livestream is public and everyone can see it, no matter what. Btw, very awesome project, thank a lot <3

Insecure Login Blocked: You can't get an access token or log in to this app from an insecure page. Try re-loading the page as https://

**Comment by bradisbell** [comment]
Yes, even accessing public posts requires you to be logged in.

Additionally, all Facebook apps created since March of 2018 require HTTPS.  (More info here:  https://developers.facebook.com/docs/facebook-login/security/)

For your own development, you can create a self-signed certificate and configure it with your web server.  For publicly accessible pages, you can get a free certificate from [Let's Encrypt](https://letsencrypt.org/)

**Comment by JustSmile739** [comment]
Ok i got the SSL and now i'm keep stuck.
I tried a hundreds of ways to post link FB, but it always warning that Your URL was not recognized.  Please post a URL to a specific post on Facebook. Can you give me an example about the link to test.
And i saw that it display the "Facebook User" but not the real name of people who join the livestream, the most important part i need. Can you give me any idea ?

**Comment by bradisbell** [comment]
If you could open a new issue and show me the URL you're trying, I will look into it.  As for the "Facebook User" issue, there have been recent Graph API changes that hide the names of those making the comments.  Pages may have access with a page access token, and there is a separate enhancement underway to enable that.
