### ISSUE TITLE
Accessing Videos from Pages

### ISSUE THREAD

**Issue by TechMonkey01** [fbsamples/live-comments-teleprompter#3]
I am trying to access Live Videos that I am posting to a Page rather than my Profile. I was able to achieve this by changing '/me/live_videos' to '/{page-id}/live_videos' on line 73 of main.js. This enabled me to see the Live Videos but the name function in the comment capture produces an error (listed below) if anyone other than the page comments on the video.

jQuery.Deferred exception: Cannot read property 'name' of undefined TypeError: Cannot read property 'name' of undefined
--

**Comment by xetaiii** [comment]
I'm trying same thing. When I change mentioned code, nothing happened. Still getting "No live video found" when I'm streaming on my fb page. I'm trying to play with fb login permissions but no luck at all.

**Comment by bradisbell** [comment]
Unfortunately, due to Graph API restrictions, it isn't possible to get the name of someone posting to a page.  Therefore, you will have to check to see if `from` was defined.  You can modify L157 of main.js from this:

```
$('<h2 class="name">').text(comment.from.name),
```

To this:

```
$('<h2 class="name">').text(
  (comment.from && comment.from.name) ? comment.from.name : 'Facebook User'
),
```

This change will add the filler content of 'Facebook User', instead of a name when the name is not present.

Proper page support (albeit with 'Facebook User' as shown above) has been added to the next release.  Please 'watch' this repo so that you will be notified when the new release is posted.

**Comment by bradisbell** [comment]
v2 adds support for pages, and has been merged to master.  Please check it out.  Thanks.
